var GPUConstant = {
    AddressMode: {},
    BindingType: {},
    BlendFactor: {},
    BlendOperation: {},
    CompareFunction: {},
    CompilationMessageType: {},
    CullMode: {},
    ErrorFilter: {},
    FeatureName: {},
    FilterMode: {},
    FrontFace: {},
    IndexFormat: {},
    InputStepMode: {},
    LoadOp: {},
    PipelineStatisticName: {},
    PowerPreference: {},
    PrimitiveTopology: {},
    QueryType: {},
    StencilOperation: {},
    StoreOp: {},
    TextureAspect: {},
    TextureComponentType: {},
    TextureDimension: {},
    TextureFormat: {},
    TextureViewDimension: {},
    VertexFormat: {},
};
